name: On Push
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Set env variables
        run: |
          echo "NODE_ENV=ci" >> $GITHUB_ENV
          echo "PORT=3000" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: npm ci && npm run build
      - name: Start server
        run: nohup npm run start &
      - name: Run tests
        run: sleep 3 && npm run test
